server:
  port: 0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dicesdb?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:    hibernate:
      ddl-auto: update
    properties:      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: rolldice-api   
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka