server:
  port: 8484
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: dice-api     
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka